version: '3'
services:
  wassim:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_USER: fryser
        HOST_USER_ID: 1000
    ports:
      - "4200:4200"
    container_name: wassim
    environment:
      CYPRESS_CACHE_FOLDER: '/var/app/googlemapscraperpro/wassim/.cypress-cache'
    restart: always
    tty: true
    volumes:
      - .:/var/app/googlemapscraperpro:rw



  # --------------------------------------------------------------------------------------------------------------------
  #
  # PORTAINER
  #
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer-googlemapscraperpro
    restart: always
    volumes:
      - ${DOCKER_SOCK_PATH}:/var/run/docker.sock:rw
      - ./portainer:/data:rw
    ports:
      - "8888:9000"
    